### PR TITLE
feat: Add support for Podfile defined platform

### PR DESCRIPTION
**Pull request by alexzchut**
Add support for the specific platform defined in Podfile (ex: `:ios`, `:tvos`).

The parameter can be passed to the `convert_frameworks_to_xcframeworks` function as `current_target_definition.platform`, default value is `:ios`

> pre_install do |installer|
>    XCFrameworkConverter.convert_frameworks_to_xcframeworks!(installer, current_target_definition.platform)
>end

### CODE REVIEW

**Comment by igor-makarov** [comment]
@alexzchut hello and welcome! Can you gave an example of a framework with tvOS binary so I can take a look?

**Comment by alexzchut** [comment]
Hi @igor-makarov, you can take a look at `GoogleAds-IMA-tvOS-SDK` version 4.4.2

**Comment by alexzchut** [comment]
@igor-makarov please also take a look into the issue I got informed about, occurs on M1 only. Wasn't reproduced on my older MacBook..
image

patching.rb, line 30:
>original_arm_slice_identifier = xcframework.slices.find do |slice|
>       slice.platform == current_platform && slice.supported_archs.include?('arm64')
>end.identifier

**Comment by igor-makarov** [comment]
@alexzchut I'll look into it.

By the way, the platform identifier should not come from a parameter but should be inferred from the binary, otherwise it won't work in all cases. 

It seems like a huge effort to get done right. To do this in a way that supports both dylibs and static libraries will take time.

**Comment by alexzchut** [comment]
@igor-makarov I see, I will also check this particular library but this error seems to be out of scope of this PR so for now it will be good to be used to support different platforms.

**Comment by igor-makarov** [comment]
@alexzchut could you rebase please? There's an accidental change to the submodule.

**Comment by alexzchut** [comment]
@igor-makarov done

**Comment by igor-makarov** [comment]
@alexzchut I've looked at it some more and I see several cases where this will fail in a confusing way:
* Pod that has multiple platforms defined with an old-style `.framework` for each platform.
* Pod that has an `.xcframework` for multiple platforms but needs patching for arm64-simulator for these platforms.

In order to proceed, we need to make sure to not rely on externally provided platform param.  
In the case of an `.framework` this needs to be inferred from the binary using `ruby-macho`.  
In the case of an `.xcframework` this can be determined by the slice metadata.

**Comment by alexzchut** [comment]
@igor-makarov 
Currently the code rely only on ios as a platform so the external parameter will override it if provided

- Pod will fetch only the old framework defined in podspec and related to the platform specified in the Podfile
- In case of xcframework, I added a fix for the platform name compare in the correct way to find matching one and skip the patching step if not needed (the identifier error I sent you before is no longer reproduced). As an example you can see the [AppCenter](https://github.com/CocoaPods/Specs/blob/master/Specs/f/9/9/AppCenter/4.4.2/AppCenter.podspec.json) podspec - it has multiple platforms support

**Comment by igor-makarov** [comment]
@alexzchut I understand, I can see that it will work under the constraints you described. 

However, I would like the external API to be forgiving and to infer anything that is possible to infer. 

I believe this won't be much extra work, I can push the changes to your branch if you want. It just might take some time since I'm a bit busy.

**Comment by alexzchut** [comment]
its ok, whenever you have time, you can push the changes to my branch

**Comment by igor-makarov** [comment]
Closing this in favor of #8

**Pull request closed without merging**
